// ingredients.ts
interface IngredientName {
  group_name: string;
  ingredients: string[];
}

const allIngredients: IngredientName[] = [
  {
    "group_name": "Pantry Essentials",
    "ingredients": [
        "butter",
        "egg",
        "garlic",
        "milk",
        "onion",
        "sugar",
        "flour",
        "olive oil",
        "garlic powder",
        "white rice",
        "cinnamon",
        "ketchup",
        "soy sauce",
        "mayonnaise",
        "vegetable oil",
        "bread",
        "baking powder",
        "brown sugar",
        "oregano",
        "potato",
        "honey",
        "paprika",
        "baking soda",
        "vanilla",
        "spaghetti",
        "peanut butter",
        "chili powder",
        "cumin",
        "mustard",
        "chicken breast",
        "cheddar",
        "onion powder",
        "carrot",
        "tomato",
        "basil",
        "parsley",
        "parmesan",
        "italian seasoning",
        "thyme",
        "bell pepper"
    ]
},
{
    "group_name": "Vegetables & Greens",
    "ingredients": [
        "garlic",
        "onion",
        "bell pepper",
        "carrot",
        "scallion",
        "tomato",
        "potato",
        "red onion",
        "celery",
        "jalapeno",
        "avocado",
        "zucchini",
        "shallot",
        "cherry tomato",
        "cucumber",
        "spinach",
        "corn",
        "chile pepper",
        "sweet potato",
        "broccoli",
        "baby greens",
        "pumpkin",
        "cauliflower",
        "asparagus",
        "cabbage",
        "arugula",
        "kale",
        "leek",
        "lettuce",
        "eggplant",
        "butternut squash",
        "romaine",
        "beetroot",
        "brussels sprout",
        "sun dried tomato",
        "fennel",
        "radish",
        "red cabbage",
        "artichoke",
        "summer squash",
        "new potato",
        "mixed greens",
        "parsnip",
        "baby carrot",
        "mixed vegetable",
        "poblano pepper",
        "sweet pepper",
        "green tomato",
        "serrano pepper",
        "iceberg",
        "watercress",
        "horseradish",
        "mashed potatoes",
        "chard",
        "hash browns",
        "pimiento",
        "butter lettuce",
        "coleslaw",
        "napa cabbage",
        "spaghetti squash",
        "celeriac",
        "turnip",
        "bok choy",
        "okra",
        "corn cob",
        "acorn squash",
        "water chestnut",
        "radicchio",
        "pearl onion",
        "pepperoncini",
        "leaf lettuce",
        "cavolo nero",
        "tenderstem broccoli",
        "baby bok choy",
        "plantain",
        "jicama",
        "collard greens",
        "habanero pepper",
        "endive",
        "corn husk",
        "french-fried onions",
        "daikon",
        "baby corn",
        "rutabaga",
        "potato flakes",
        "belgian endive",
        "broccoli rabe",
        "kohlrabi",
        "fresno chile",
        "microgreens",
        "yam",
        "ancho chile peppers",
        "boston lettuce",
        "delicata squash",
        "anaheim pepper",
        "cress",
        "frisee",
        "broccoli slaw",
        "golden beet",
        "banana pepper"
    ]
},
{
    "group_name": "Mushrooms",
    "ingredients": [
        "button mushroom",
        "shiitake mushroom",
        "portobello mushroom",
        "wild mushroom",
        "porcini",
        "oyster mushroom",
        "mixed mushrooms",
        "chestnut mushroom",
        "enoki mushroom",
        "black fungus",
        "morel mushrooms",
        "black truffle",
        "king oyster mushroom",
        "shimeji mushroom",
        "straw mushroom",
        "field mushroom",
        "dried chinese mushroom",
        "maitake",
        "trumpet mushroom",
        "white truffle",
        "white fungus",
        "pioppini",
        "snow fungus",
        "white beech mushroom",
        "huitlacoche",
        "matsutake",
        "nameko",
        "boletus",
        "djon djon mushroom",
        "puffball",
        "bamboo fungus",
        "honey fungus",
        "lobster mushroom",
        "mixed asian mushrooms",
        "saffron milk caps",
        "caesar's mushroom",
        "candy cap mushrooms",
        "lion\u2019s mane mushroom"
    ]
},
{
    "group_name": "Fruits",
    "ingredients": [
        "lemon",
        "lime",
        "apple",
        "banana",
        "orange",
        "raisins",
        "mango",
        "pineapple",
        "peach",
        "date",
        "craisins",
        "coconut",
        "pear",
        "pomegranate",
        "grape",
        "watermelon",
        "rhubarb",
        "dried apricot",
        "kiwi",
        "grapefruit",
        "plum",
        "fig",
        "apricot",
        "mandarin",
        "currant",
        "prunes",
        "cantaloupe",
        "sultanas",
        "passion fruit",
        "papaya",
        "tamarind",
        "nectarine",
        "dried fig",
        "chestnut",
        "meyer lemon",
        "dried fruit",
        "honeydew melon",
        "clementine",
        "persimmon",
        "melon",
        "dried mango",
        "tangerine",
        "dried apple",
        "quince",
        "banana chips",
        "kumquat",
        "guava",
        "jackfruit",
        "mixed fruit",
        "asian pear",
        "dragon fruit",
        "dried pineapple",
        "lychee",
        "young coconut",
        "kaffir lime",
        "star fruit",
        "green mango",
        "green papaya",
        "dried pears",
        "pomelo",
        "calamansi",
        "chestnut puree",
        "prickly pear",
        "apple chips",
        "yuzu",
        "granadilla",
        "dried peach",
        "mixed peel",
        "kokum",
        "dried lime",
        "tangelo",
        "jujube",
        "dried lemon",
        "honey date",
        "young jackfruit",
        "custard-apple",
        "durian",
        "sweet lime",
        "freeze-dried apple",
        "wood apple",
        "dried tamarind",
        "tamarillo",
        "longan",
        "physalis",
        "finger lime",
        "ice-apple",
        "bitter orange",
        "feijoa",
        "chikoo",
        "dried persimmons",
        "rambutan",
        "crabapple",
        "dried orange slice",
        "fig leaves",
        "rose apple",
        "loquat",
        "pluot",
        "freeze-dried pineapple",
        "soursop",
        "bergamot orange"
    ]
},
{
    "group_name": "Berries",
    "ingredients": [
        "strawberry",
        "blueberry",
        "raspberry",
        "cranberry",
        "cherry",
        "blackberry",
        "berry mix",
        "dried cherry",
        "sour cherry",
        "dried blueberries",
        "goji berry",
        "freeze-dried strawberry",
        "gooseberry",
        "freeze-dried raspberry",
        "lingonberry",
        "acai berry",
        "mulberry",
        "amla",
        "elderberry",
        "freeze-dried blueberry",
        "huckleberry",
        "dried elderberry",
        "barberry",
        "black raspberry",
        "dried berries",
        "boysenberry",
        "rosehip",
        "saskatoon berry",
        "hawthorn",
        "sea buckthorn",
        "cloudberry",
        "freeze-dried berries",
        "chokeberry",
        "aronia berry",
        "loganberry",
        "acerola",
        "blackcurrant leaves",
        "haskap berry",
        "sloe berry",
        "oregon grape"
    ]
},
{
    "group_name": "Nuts & Seeds",
    "ingredients": [
        "walnut",
        "pecan",
        "almond",
        "sesame seed",
        "cashew",
        "pine nut",
        "pistachio",
        "peanut",
        "chia",
        "slivered almonds",
        "pumpkin seeds",
        "hazelnut",
        "poppy seed",
        "sunflower seeds",
        "flax",
        "chopped nuts",
        "macadamia",
        "roasted peanuts",
        "hemp hearts",
        "roasted almonds",
        "nigella seeds",
        "mixed nuts",
        "brazil nut",
        "mixed seeds",
        "smoked almond",
        "onion seed",
        "watermelon seeds",
        "candied walnut",
        "honey-roasted peanuts",
        "melon seeds",
        "black walnut",
        "lotus seeds",
        "white chia",
        "trail mix",
        "basil seeds",
        "candlenut",
        "peanut brittle",
        "jackfruit seeds",
        "chironji",
        "honey-roasted almond",
        "honey-roasted pecans",
        "toasted nuts",
        "soy nuts",
        "sriracha almond",
        "tigernuts",
        "chia powder",
        "sunflower sprouts",
        "apricot kernels",
        "honey-roasted cashew",
        "milk thistle seeds",
        "ginkgo nuts",
        "palm seeds",
        "keto trail mix",
        "pine cone",
        "wattleseeds",
        "bar\u00f9kas",
        "indian almond"
    ]
},
{
    "group_name": "Cheeses",
    "ingredients": [
        "parmesan",
        "cream cheese",
        "cheddar",
        "mozzarella",
        "feta",
        "sharp cheddar",
        "ricotta",
        "monterey jack",
        "blue cheese",
        "goat cheese",
        "fresh mozzarella",
        "swiss cheese",
        "pecorino",
        "gruyere",
        "mascarpone",
        "cottage cheese",
        "american cheese",
        "provolone",
        "mexican cheese blend",
        "pepper jack",
        "brie",
        "paneer",
        "fontina",
        "queso fresco",
        "quark",
        "gouda",
        "cotija",
        "asiago",
        "smoked cheese",
        "halloumi",
        "chevre",
        "italian cheese blend",
        "neufchatel",
        "manchego",
        "herb cream cheese",
        "havarti",
        "colby",
        "burrata",
        "grana-padano",
        "muenster",
        "string cheese",
        "camembert",
        "soft cheese",
        "stilton",
        "raclette",
        "cheddar-jack cheese",
        "colby-jack cheese",
        "jarlsberg cheese",
        "taleggio",
        "creamy cheese wedge",
        "labneh",
        "edam",
        "oaxaca",
        "baby swiss cheese",
        "fromage blanc",
        "curd cheese",
        "marble cheese",
        "kefalotyri",
        "mizithra",
        "seasoned feta cheese",
        "asadero",
        "kasseri",
        "leicester",
        "sheep cheese",
        "lancashire",
        "babybel",
        "scamorza",
        "longhorn",
        "comt\u00e9",
        "graviera",
        "wensleydale",
        "cambozola",
        "chenna",
        "cheshire cheese",
        "anthotyro",
        "dubliner cheese",
        "garlic-and-herb goat cheese",
        "hard goat cheese",
        "kashkaval",
        "amul cheese",
        "reblochon",
        "robiola",
        "brick cheese",
        "queso quesadilla",
        "quick-melt cheese",
        "manouri",
        "mimolette",
        "panela cheese",
        "stracchino cheese",
        "bergk\u00e4se",
        "caciocavallo",
        "farmer's cheese",
        "fontal",
        "polish farmer's cheese",
        "vacherin",
        "derby cheese",
        "flemish cheese",
        "gloucester",
        "truffle cheese",
        "brown cheese"
    ]
},
{
    "group_name": "Dairy & Eggs",
    "ingredients": [
        "butter",
        "egg",
        "milk",
        "heavy cream",
        "sour cream",
        "buttermilk",
        "yogurt",
        "greek yogurt",
        "cream",
        "whipped cream",
        "ghee",
        "shortening",
        "half and half",
        "sweetened condensed milk",
        "condensed milk",
        "ice cream",
        "margarine",
        "creme fraiche",
        "frosting",
        "milk powder",
        "curd",
        "thickened cream",
        "lemon curd",
        "custard",
        "dulce de leche",
        "liquid egg substitute",
        "chocolate frosting",
        "kefir",
        "sherbet",
        "chocolate milk",
        "hung curd",
        "fried eggs",
        "whey",
        "quail egg",
        "buttermilk powder",
        "frozen yogurt",
        "khoya",
        "poached eggs",
        "coffee creamer",
        "clotted cream",
        "cheese curd",
        "milk cream",
        "goat milk",
        "sour milk",
        "ganache",
        "scrambled eggs",
        "duck egg",
        "egg white powder",
        "salted egg",
        "skyr",
        "pumpkin spice coffee creamer",
        "yogurt starter",
        "honey greek yogurt",
        "raw milk",
        "lime curd",
        "powdered coffee creamer",
        "milkfat",
        "rainbow sherbet",
        "strawberry frosting",
        "amul butter",
        "cajeta",
        "goat yogurt",
        "honey butter",
        "strawberry cream cheese",
        "goat butter",
        "cookies n' cream ice cream",
        "passionfruit curd",
        "century egg",
        "orange curd",
        "starter culture",
        "dahi",
        "cinnamon sugar butter spread",
        "bulgarian yogurt",
        "egg powder",
        "key lime yogurt",
        "peppermint mocha creamer",
        "tvorog",
        "chantilly",
        "liquid rennet",
        "chocolate milk powder",
        "sheep\u2019s milk yoghurt",
        "strawberry milk",
        "ayran",
        "buffalo milk",
        "yogurt drink",
        "cuajada",
        "evaporated goat milk",
        "sheep milk",
        "vanilla milk",
        "pickled egg",
        "yoplait whips",
        "goat kefir",
        "kashk",
        "lebneh",
        "niter kibbeh",
        "ostrich egg"
    ]
},
{
    "group_name": "Dairy-Free & Meat Substitutes",
    "ingredients": [
        "coconut milk",
        "almond milk",
        "almond butter",
        "tofu",
        "vegan butter",
        "coconut cream",
        "non-dairy milk",
        "soy milk",
        "extra firm tofu",
        "silken tofu",
        "coconut butter",
        "kala namak salt",
        "egg replacer",
        "vegan mayonnaise",
        "cashew butter",
        "tempeh",
        "vegan cream cheese",
        "coconut yogurt",
        "vegan parmesan",
        "non-dairy yogurt",
        "seed butter",
        "vegan cheese",
        "cashew milk",
        "nut butter",
        "oat milk",
        "rice milk",
        "vegan sour cream",
        "textured vegetable protein",
        "vegan worcestershire",
        "non-dairy creamer",
        "vegan mozzarella",
        "soy yogurt",
        "non-dairy cream",
        "coconut whipped cream",
        "vegan sausage",
        "smoked tofu",
        "seitan",
        "coconut milk powder",
        "nut milk",
        "non-dairy whipped topping",
        "vegan ground beef",
        "condensed coconut milk",
        "vegan burger patty",
        "chocolate almond milk",
        "vegan bacon",
        "vegan pesto",
        "vegan feta",
        "soy chorizo",
        "soy curls",
        "vegan ranch",
        "vegetarian oyster sauce",
        "hazelnut butter",
        "hemp milk",
        "vegan beef",
        "dairy-free ice-cream",
        "vegan chicken",
        "coconut paste",
        "marinated tofu",
        "vegetable suet",
        "almond-coconut milk",
        "vegan fish sauce",
        "vegetarian hot dog",
        "hazelnut milk",
        "vegan caesar dressing",
        "almond pulp",
        "vegan meatballs",
        "maple almond butter",
        "almond creamer",
        "almond-milk yogurt",
        "soy milk powder",
        "vegan cream cheese frosting",
        "macadamia butter",
        "coconut bacon",
        "vegan gravy",
        "cashew cheese sauce",
        "falafel mix",
        "soy-free butter",
        "vegan nutella",
        "cashewgurt",
        "coconut fat",
        "hazelnut creamer",
        "tofurky",
        "vegan tzatziki",
        "cashew cream cheese",
        "coconut cream powder",
        "flax milk",
        "quorn",
        "cricket flour",
        "okara",
        "vegan ham",
        "cashew sour cream",
        "egg tofu",
        "macadamia milk",
        "vegan taco meat",
        "walnut taco meat",
        "ready-made falafel",
        "vegan queso",
        "vegan yogurt starter",
        "banana milk",
        "latik"
    ]
},
{
    "group_name": "Meats",
    "ingredients": [
        "bacon",
        "ground beef",
        "beef steak",
        "deli ham",
        "pork chops",
        "sweet italian sausage",
        "pork fillet",
        "prosciutto",
        "beef roast",
        "ground pork",
        "sausage",
        "beef stew meat",
        "pepperoni",
        "chorizo",
        "pancetta",
        "pork shoulder",
        "pork loin",
        "ground lamb",
        "smoked sausage",
        "pork ribs",
        "breakfast sausage",
        "hot dog",
        "beef sirloin",
        "salami",
        "brisket",
        "kielbasa",
        "leg of lamb",
        "beef short ribs",
        "pork belly",
        "andouille",
        "hot italian sausage",
        "boneless lamb",
        "ground pork sausage",
        "pork roast",
        "ground sausage",
        "roast beef",
        "bone-in ham",
        "bacon bits",
        "pork spare ribs",
        "lamb chops",
        "beef ribs",
        "lamb shoulder",
        "veal steak",
        "pork butt",
        "canadian bacon",
        "beef sausage",
        "mutton",
        "lamb shank",
        "pulled pork",
        "venison",
        "ham steak",
        "bratwurst",
        "mixed ground meat",
        "frozen meatballs",
        "ham hock",
        "pork cutlets",
        "rabbit",
        "veal cutlet",
        "lamb loin",
        "country style ribs",
        "mexican chorizo",
        "pork back ribs",
        "smoked ham hock",
        "black forest ham",
        "soup bones",
        "oxtail",
        "raw chorizo",
        "rack of lamb",
        "beef liver",
        "serrano ham",
        "pastrami",
        "cocktail sausage",
        "hard salami",
        "salt pork",
        "boneless ham",
        "veal shank",
        "back bacon",
        "ground venison",
        "lap cheong",
        "dried beef",
        "blood sausage",
        "beef shank",
        "fresh sausage",
        "mortadella",
        "country ham",
        "boneless beef short ribs",
        "gammon joint",
        "cooked pork",
        "ground bison",
        "bologna",
        "burger patty",
        "smoked pork chop",
        "sausage patty",
        "lamb neck",
        "veal roast",
        "beef shoulder",
        "pork neck",
        "pork stew meat",
        "beef suet",
        "steak tips"
    ]
},
{
    "group_name": "Poultry",
    "ingredients": [
        "chicken breast",
        "cooked chicken",
        "chicken thighs",
        "boneless skinless chicken thighs",
        "ground turkey",
        "whole chicken",
        "chicken wings",
        "whole turkey",
        "chicken leg",
        "turkey breast",
        "ground chicken",
        "rotisserie chicken",
        "chicken tenders",
        "turkey sausage",
        "chicken sausage",
        "turkey bacon",
        "duck",
        "duck breast",
        "deli turkey",
        "cornish hen",
        "chicken livers",
        "smoked turkey",
        "turkey meat",
        "roasted turkey",
        "chicken quarters",
        "ground turkey sausage",
        "quail",
        "roasted turkey breast",
        "smoked turkey sausage",
        "smoked chicken",
        "turkey leg",
        "goose",
        "pheasant",
        "turkey pepperoni",
        "turkey thigh",
        "chicken bones",
        "chicken nuggets",
        "foie gras",
        "turkey meatballs",
        "chicken giblets",
        "turkey wing",
        "turkey giblets",
        "turkey neck",
        "turkey burger",
        "chicken andouille",
        "chicken gizzards",
        "smoked turkey leg",
        "popcorn chicken",
        "chicken italian sausage",
        "ostrich",
        "turkey kielbasa",
        "chicken feet",
        "chicken-apple sausage",
        "deli chicken",
        "smoked duck breast",
        "pulled chicken",
        "wild game bird",
        "chicken necks",
        "duck confit",
        "pigeon",
        "turkey liver",
        "roast duck",
        "chicken meatballs",
        "chicken teriyaki",
        "smoked turkey wings",
        "duck liver",
        "guinea fowl",
        "chicken curry-cut",
        "chicken schnitzel",
        "turkey lunch meat",
        "chicken roast",
        "goose liver",
        "grouse",
        "turkey roast",
        "capon",
        "turkey bones",
        "young chicken",
        "cooked duck",
        "smoked turkey bacon",
        "chicken bacon",
        "chicken hot dog",
        "parmesan-crusted chicken",
        "leftover fried chicken",
        "turkey hot dog",
        "turkey rissoles",
        "smoked turkey neck",
        "chicken ham",
        "chicken chorizo",
        "turkey taco meat",
        "chicken frames",
        "duck neck",
        "pulled turkey",
        "chicken gyros",
        "chicken kebab",
        "chicken patty",
        "chicken ribs",
        "duck bacon",
        "turkey tail"
    ]
},
{
    "group_name": "Fish",
    "ingredients": [
        "salmon",
        "smoked salmon",
        "cod",
        "tilapia",
        "tuna steak",
        "whitefish",
        "halibut",
        "red snapper",
        "sea bass",
        "trout",
        "fish fillets",
        "catfish",
        "surimi",
        "swordfish",
        "sardines",
        "mahi mahi",
        "sole",
        "smoked trout",
        "mackerel",
        "haddock",
        "caviar",
        "monkfish",
        "smoked haddock",
        "flounder",
        "hot-smoked salmon",
        "hake",
        "perch",
        "salt cod",
        "pollock",
        "smoked mackerel",
        "sea bream",
        "rainbow trout",
        "cuttlefish",
        "grouper",
        "herring",
        "carp",
        "salmon roe",
        "steelhead trout",
        "roe",
        "barramundi",
        "black cod",
        "orange roughy",
        "kingfish",
        "turbot",
        "dried anchovy",
        "rockfish",
        "pomfret",
        "bangus",
        "branzino",
        "battered fish",
        "arctic char",
        "coho salmon",
        "lemon sole",
        "eel",
        "fresh anchovy",
        "pike",
        "swai fish",
        "walleye",
        "yellowtail",
        "john dory",
        "fresh mackerel",
        "salmon trout",
        "smoked eel",
        "basa fish",
        "sturgeon",
        "bluefish",
        "red mullet",
        "fish balls",
        "gurnard",
        "ocean perch",
        "plaice",
        "pompano",
        "rohu fish",
        "salt fish",
        "smoked fish",
        "fish cake",
        "salted salmon",
        "dried fish",
        "fish heads",
        "smoked herring",
        "whiting",
        "flathead",
        "nile perch",
        "salmon burger meat",
        "shark meat",
        "smoked tuna",
        "garoupa",
        "gilt-head bream",
        "zander",
        "alaskan pollock",
        "amberjack",
        "pangasius",
        "salt herring",
        "soused herring",
        "korean fish cake",
        "mullet",
        "bottarga",
        "galunggong",
        "skipjack tuna",
        "tinapa"
    ]
},
{
    "group_name": "Seafood & Seaweed",
    "ingredients": [
        "shrimp",
        "prawns",
        "crab",
        "scallop",
        "mussel",
        "clam",
        "squid",
        "nori",
        "lobster",
        "oyster",
        "lobster tail",
        "crawfish",
        "octopus",
        "dried shrimp",
        "kombu",
        "bay scallop",
        "wakame",
        "soft-shell crab",
        "scampi",
        "baby squid",
        "mixed seafood",
        "king crab",
        "dried scallops",
        "squid ink",
        "dulse seaweed",
        "bay shrimp",
        "kelp",
        "yaki-nori",
        "roasted seaweed",
        "smoked oyster",
        "kizami nori",
        "hijiki",
        "conch",
        "salted shrimp",
        "calamari steak",
        "mud crab",
        "arame",
        "sea urchin",
        "seaweed salad",
        "abalone",
        "dulse",
        "spanner crab",
        "dried squid",
        "smoked mussel",
        "aonori",
        "imitation lobster",
        "prepared crab cake",
        "sea snails",
        "korean seaweed",
        "sea lettuce",
        "ground shrimp",
        "jellyfish",
        "ogo seaweed",
        "seaweed caviar",
        "shredded squid",
        "sea moss",
        "langoustine"
    ]
},
{
    "group_name": "Herbs & Spices",
    "ingredients": [
        "cinnamon",
        "parsley",
        "cilantro",
        "cumin",
        "basil",
        "thyme",
        "ginger root",
        "garlic powder",
        "oregano",
        "nutmeg",
        "chili flake",
        "chili powder",
        "paprika",
        "cayenne",
        "rosemary",
        "bay leaf",
        "turmeric",
        "clove",
        "onion powder",
        "ginger powder",
        "dill",
        "chive",
        "mint",
        "green cardamom",
        "smoked paprika",
        "fresh mint",
        "coriander powder",
        "sage",
        "coriander",
        "allspice",
        "cracked pepper",
        "mustard powder",
        "peppercorn",
        "white pepper",
        "mustard seed",
        "curry leaves",
        "fennel seed",
        "tarragon",
        "saffron",
        "asafoetida",
        "star anise",
        "marjoram",
        "lemongrass",
        "caraway",
        "garlic granules",
        "celery seed",
        "chipotle powder",
        "chipotle",
        "fenugreek",
        "onion flake",
        "thai chile pepper",
        "ancho chile powder",
        "sumac",
        "dried parsley flakes",
        "fenugreek seed",
        "kashmiri red chilli",
        "thai basil",
        "edible flowers",
        "kaffir lime leaves",
        "aniseed",
        "chervil",
        "lavender",
        "carom seeds",
        "mango powder",
        "mace",
        "dried chives",
        "mexican oregano",
        "black mustard seed",
        "black cardamom",
        "dried chilies",
        "saffron strands",
        "pink peppercorn",
        "hot paprika",
        "roasted cumin powder",
        "guajillo pepper",
        "lemon thyme",
        "turmeric root",
        "dried cilantro",
        "galangal",
        "lemon balm",
        "garlic flakes",
        "dill seed",
        "aleppo pepper",
        "green peppercorn",
        "wasabi powder",
        "gochugaru",
        "savory herb",
        "clove powder",
        "achiote seeds",
        "pandan leaves",
        "sorrel",
        "greek oregano",
        "saigon cinnamon",
        "lemongrass paste",
        "shiso",
        "celery powder",
        "anardana",
        "black cumin",
        "dried orange peel",
        "espelette pepper"
    ]
},
{
    "group_name": "Sugar & Sweeteners",
    "ingredients": [
        "sugar",
        "brown sugar",
        "confectioners\u2019 sugar",
        "honey",
        "maple syrup",
        "corn syrup",
        "coconut sugar",
        "molasses",
        "stevia",
        "agave nectar",
        "demerara sugar",
        "sugar syrup",
        "erythritol",
        "vanilla sugar",
        "caramel syrup",
        "chocolate syrup",
        "jaggery",
        "golden syrup",
        "cinnamon sugar",
        "liquid stevia",
        "grenadine",
        "coarse sugar",
        "salted caramel syrup",
        "sanding sugar",
        "dark corn syrup",
        "monk fruit sweetener",
        "sucralose",
        "colored sugar",
        "blackstrap molasses",
        "maple sugar",
        "confectioners' sweetener",
        "glucose",
        "xylitol",
        "brown sugar substitute",
        "brown rice syrup",
        "jam sugar",
        "rock sugar",
        "vanilla syrup",
        "strawberry syrup",
        "coconut syrup",
        "ginger syrup",
        "orgeat",
        "raspberry syrup",
        "date syrup",
        "pancake syrup",
        "rice malt syrup",
        "black treacle",
        "date paste",
        "mint syrup",
        "cinnamon syrup",
        "passion fruit syrup",
        "treacle",
        "rice syrup",
        "maple butter",
        "manuka honey",
        "blueberry syrup",
        "apple syrup",
        "allulose",
        "blackberry syrup",
        "hibiscus syrup",
        "cherry syrup",
        "fresh sugar cane",
        "lavender syrup",
        "white chocolate sauce",
        "pineapple syrup",
        "sorghum syrup",
        "hazelnut syrup",
        "piloncillo",
        "pumpkin spice syrup",
        "glycerine",
        "cranberry syrup",
        "golden sugar",
        "jaggery syrup",
        "black sugar",
        "cane syrup",
        "malt syrup",
        "mango syrup",
        "gula melaka",
        "hot honey",
        "elderberry syrup",
        "rosemary syrup",
        "dark chocolate syrup",
        "inulin",
        "brown butter syrup",
        "flavored stevia",
        "sweet'n low",
        "honey powder",
        "fructose",
        "berry syrup",
        "date sugar",
        "grape syrup",
        "gum syrup",
        "irish cream syrup",
        "mastic gum",
        "prickly pear syrup",
        "cookie butter syrup",
        "creamed honey",
        "gingerbread syrup",
        "chocolate sugar",
        "buttermilk syrup"
    ]
},
{
    "group_name": "Seasonings & Spice Blends",
    "ingredients": [
        "italian seasoning",
        "seasoned salt",
        "curry",
        "garam masala",
        "pumpkin pie spice",
        "taco seasoning",
        "cajun seasoning",
        "dry ranch seasoning",
        "white miso",
        "himalayan salt",
        "lemon & pepper seasoning",
        "liquid smoke",
        "poultry seasoning",
        "old bay seasoning",
        "chinese five spice",
        "red curry",
        "herbes de provence",
        "all-purpose seasoning",
        "chaat masala",
        "creole seasoning",
        "steak seasoning",
        "juniper berry",
        "fleur de sel",
        "thai red curry paste",
        "mixed herbs",
        "green curry",
        "barbecue seasoning",
        "apple pie spice",
        "za'atar",
        "ras el hanout",
        "bagel seasoning",
        "chili con carne seasoning",
        "fajita seasoning",
        "gravy mix",
        "tandoori spice",
        "pickling spice",
        "garlic-pepper seasoning",
        "caribbean jerk seasoning",
        "pickling salt",
        "garlic & herb seasoning",
        "greek seasoning",
        "msg",
        "adobo seasoning",
        "seafood seasoning",
        "sambar powder",
        "smoked salt",
        "smoking wood",
        "dash seasoning",
        "red miso",
        "chili-lime seasoning",
        "hot curry",
        "salt-free seasoning",
        "bouquet garni",
        "carne asada seasoning",
        "yellow miso",
        "curing salt",
        "pav bhaji masala",
        "dukkah",
        "mexican seasoning",
        "seasoned pepper",
        "truffle salt",
        "shichimi togarashi",
        "rib rub",
        "biryani masala",
        "chipotle seasoning",
        "furikake",
        "chana masala",
        "meat masala",
        "togarashi",
        "harissa spice blend",
        "cheese powder",
        "grey sea salt",
        "gingerbread spice",
        "brown miso",
        "au jus mix",
        "mushroom seasoning",
        "popcorn seasoning",
        "pizza seasoning",
        "berbere",
        "blackening seasoning",
        "lemon & herb seasoning",
        "chai masala",
        "panang curry",
        "kitchen king masala",
        "shawarma seasoning",
        "fines herbes",
        "vanilla salt",
        "thai seasoning",
        "mulling spices",
        "coffee rub",
        "hawaiian salt",
        "southwest seasoning",
        "sriracha seasoning",
        "tom yum paste",
        "guacamole seasoning",
        "mesquite seasoning",
        "salad seasoning",
        "beef stew seasoning",
        "baharat",
        "fish masala"
    ]
},
{
    "group_name": "Baking",
    "ingredients": [
        "flour",
        "vanilla",
        "baking powder",
        "baking soda",
        "cornstarch",
        "yeast",
        "dark chocolate chips",
        "chocolate chips",
        "whole-wheat flour",
        "shredded coconut",
        "almond flour",
        "self-raising flour",
        "cornmeal",
        "pastry flour",
        "baking mix",
        "coconut flake",
        "coconut flour",
        "cream of tartar",
        "cake flour",
        "bread flour",
        "almond meal",
        "unbleached all-purpose flour",
        "white baking chips",
        "flaxseed meal",
        "gluten-free flour",
        "rice flour",
        "tapioca starch",
        "yellow cake mix",
        "chickpea flour",
        "xanthan gum",
        "oat flour",
        "whole-wheat pastry flour",
        "candy sprinkles",
        "chocolate cake mix",
        "spelt",
        "brownie mix",
        "arrowroot flour",
        "butterscotch chips",
        "potato starch",
        "peanut butter chips",
        "crystallized ginger",
        "buckwheat flour",
        "pectin",
        "brown rice flour",
        "rye flour",
        "psyllium husk",
        "semolina flour",
        "glutinous rice flour",
        "refined flour",
        "sweetened coconut flake",
        "pancake mix",
        "marzipan",
        "toffee bits",
        "corn muffin mix",
        "coffee bean",
        "cornbread mix",
        "masa harina",
        "spice cake mix",
        "sorghum flour",
        "cinnamon chips",
        "red velvet cake mix",
        "baking chips",
        "sugar cookie mix",
        "sago",
        "matzo meal",
        "whipped cream stabilizer",
        "vital wheat gluten",
        "coconut chips",
        "cassava flour",
        "hazelnut flour",
        "finger millet flour",
        "quinoa flour",
        "meringue powder",
        "mint baking chips",
        "angel food cake mix",
        "fondant",
        "white cornmeal",
        "gluten-free baking flour",
        "millet flour",
        "einkorn flour",
        "mincemeat",
        "self-rising cornmeal",
        "peanut flour",
        "gluten-free cake mix",
        "gluten-free self-raising flour",
        "coconut powder",
        "carob powder",
        "teff flour",
        "potato flour",
        "sweet bean paste",
        "fruit salt",
        "guar gum",
        "ready-made icing",
        "tapioca pearls",
        "soy flour",
        "oat fiber",
        "instant flour",
        "amaranth flour",
        "gluten-free panko",
        "seasoned flour"
    ]
},
{
    "group_name": "Pre-Made Doughs & Wrappers",
    "ingredients": [
        "pie crust",
        "puff pastry",
        "pizza crust",
        "refrigerated crescent rolls",
        "phyllo",
        "biscuit dough",
        "dumpling wrapper",
        "rice paper",
        "sourdough starter",
        "graham cracker crust",
        "cookie dough",
        "egg roll wrapper",
        "bread dough",
        "butter puff pastry",
        "chocolate chip cookie dough",
        "frozen dinner roll",
        "mini phyllo",
        "wontons",
        "cinnamon roll dough",
        "dosa batter",
        "gyoza wrapper",
        "puff pastry shells",
        "wonton strips",
        "gluten-free pizza crust",
        "peanut butter cookie dough",
        "fresh pasta dough",
        "idli batter",
        "chocolate pie crust",
        "croissant dough",
        "kataifi",
        "sausage rolls",
        "tofu skins",
        "chocolate crumb crust",
        "brisee",
        "frozen pizza rolls",
        "korean rice cake",
        "corn dogs",
        "empanada wrapper",
        "masa dough",
        "rough-puff pastry",
        "sourdough discard",
        "gingerbread cookie dough",
        "edible chocolate chip cookie dough",
        "gluten-free peanut butter cookie dough",
        "gluten-free chocolate chip cookie dough",
        "yufka",
        "refrigerated oatmeal raisin cookies",
        "egg wrap",
        "samosa sheet",
        "brick pastry"
    ]
},
{
    "group_name": "Grains & Cereals",
    "ingredients": [
        "rolled oats",
        "white rice",
        "long-grain white rice",
        "quinoa",
        "brown rice",
        "quick-cooking oats",
        "cooked rice",
        "breakfast cereal",
        "risotto rice",
        "rice cereal",
        "couscous",
        "wild rice",
        "semolina",
        "jasmine rice",
        "polenta",
        "granola cereal",
        "bulgur",
        "cauliflower rice",
        "pearl barley",
        "farro",
        "grits",
        "barley",
        "steel cut oats",
        "wheat germ",
        "oat bran",
        "sushi rice",
        "instant rice",
        "millet",
        "glutinous rice",
        "hominy",
        "red quinoa",
        "brown basmati rice",
        "wheat bran",
        "raw buckwheat",
        "instant oats",
        "wheat berries",
        "poha",
        "yellow rice",
        "black rice",
        "muesli",
        "fine semolina",
        "kasha",
        "quinoa flakes",
        "amaranth",
        "puffed rice",
        "cracked wheat",
        "pearled farro",
        "paella rice",
        "freekeh",
        "sorghum",
        "red rice",
        "idli rice",
        "mexican rice",
        "brown jasmine rice",
        "cream of wheat",
        "rice pilaf",
        "barnyard millet",
        "weetabix",
        "blue cornmeal",
        "jambalaya rice mix",
        "whole-grain oats",
        "dirty rice mix",
        "cilantro lime rice",
        "black glutinous rice",
        "hulled barley",
        "puffed quinoa",
        "finger millet",
        "puffed wheat",
        "broccoli rice",
        "foxtail millet",
        "fried rice",
        "pearl millet",
        "matta rice",
        "rye berries",
        "kodo millet",
        "spelt flakes",
        "teff",
        "oat groats",
        "sprouted brown rice",
        "chicken-flavor rice",
        "little millet",
        "puffed amaranth",
        "rye flakes",
        "biriyani rice",
        "coconut rice",
        "red beans & rice mix",
        "rice bran",
        "spelt berry",
        "texmati rice",
        "amaranth flakes",
        "puffed kamut",
        "bamboo rice",
        "pearled sorghum",
        "shirataki rice",
        "red rice poha",
        "sona masoori rice",
        "gr\u00fcnkern",
        "jeera rice",
        "saffron rice",
        "samp"
    ]
},
{
    "group_name": "Legumes",
    "ingredients": [
        "peas",
        "green beans",
        "black beans",
        "chickpea",
        "white beans",
        "lentils",
        "kidney beans",
        "snow peas",
        "snap peas",
        "red lentils",
        "cannellini beans",
        "bean sprouts",
        "edamame",
        "pinto beans",
        "green lentils",
        "urad dal",
        "chana dal",
        "lima beans",
        "black-eyed peas",
        "fava beans",
        "moong dal",
        "split peas",
        "pigeon peas",
        "red beans",
        "mung bean sprout",
        "pea shoots",
        "soybeans",
        "string beans",
        "mung beans",
        "yellow split peas",
        "black lentils",
        "borlotti beans",
        "chana",
        "aquafaba",
        "baby lima beans",
        "snake beans",
        "yellow lentils",
        "fermented black beans",
        "kala chana",
        "mixed beans",
        "black gram",
        "dried peas",
        "wax beans",
        "white pea",
        "lentil sprouts",
        "field peas",
        "black soybeans",
        "gigantes",
        "pink beans",
        "flageolets",
        "horse gram",
        "green chickpea",
        "soy sprouts",
        "brown beans",
        "cluster beans",
        "mayocoba beans",
        "winged beans",
        "castelluccio lentils",
        "golden wax beans",
        "moth beans",
        "hara chana",
        "hyacinth beans",
        "lupini beans",
        "natto",
        "chickpea sprouts",
        "petai",
        "scarlet runner beans",
        "sugar beans",
        "honey beans",
        "soy flakes"
    ]
},
{
    "group_name": "Pasta",
    "ingredients": [
        "short-cut pasta",
        "spaghetti",
        "macaroni",
        "egg noodle",
        "lasagna",
        "spiral pasta",
        "linguine",
        "fettuccine",
        "orzo",
        "pasta shell",
        "bow-tie pasta",
        "tortellini",
        "noodle",
        "rice noodles",
        "rigatoni",
        "gnocchi",
        "angel hair pasta",
        "ramen noodles",
        "vermicelli",
        "tagliatelle",
        "ziti",
        "ravioli",
        "soba noodles",
        "israeli couscous",
        "orecchiette",
        "zoodles",
        "udon noodles",
        "ditalini",
        "gluten-free pasta",
        "rice vermicelli",
        "pappardelle",
        "glass noodles",
        "mac 'n cheese",
        "manicotti",
        "penne rigate",
        "bucatini",
        "cannelloni",
        "thai rice noodles",
        "campanelle",
        "rotelle",
        "chicken ramen",
        "brown rice pasta",
        "shirataki noodles",
        "pierogi",
        "soup pasta",
        "cavatelli",
        "sweet potato noodles",
        "acini di pepe",
        "instant noodle",
        "radiatore",
        "somen noodles",
        "gluten-free noodles",
        "yakisoba noodles",
        "beef ravioli",
        "spaetzle",
        "hakka noodles",
        "fideo pasta",
        "kluski noodles",
        "kelp noodles",
        "rice-a-roni",
        "paccheri",
        "pasta salad mix",
        "semiya",
        "beef ramen",
        "yolk-free noodles",
        "black bean pasta",
        "matzo farfel",
        "spinach fettuccine",
        "banh pho",
        "potato dumplings",
        "frozen dumplings",
        "fregola",
        "beef tortellini",
        "misua",
        "cauliflower gnocchi",
        "butternut squash noodles",
        "palmini",
        "gluten-free orzo",
        "trahanas",
        "busiate",
        "lobster ravioli",
        "mafalde",
        "trottole",
        "casarecce",
        "mandu",
        "pork ramen",
        "pot pie noodle",
        "gluten-free ramen noodles",
        "mie noodle",
        "bean pasta",
        "bean sheets",
        "hilopites",
        "jjolmyeon",
        "naengmyeon noodles",
        "quinoa pasta",
        "squash ravioli",
        "yuba noodles",
        "high-protein pasta"
    ]
},
{
    "group_name": "Bread & Salty Snacks",
    "ingredients": [
        "bread",
        "bread crumbs",
        "panko",
        "flour tortillas",
        "corn tortillas",
        "crackers",
        "baguette",
        "tortilla chips",
        "pretzels",
        "pita",
        "seasoned bread crumbs",
        "sourdough bread",
        "popcorn",
        "rustic italian bread",
        "croutons",
        "whole-wheat tortillas",
        "english muffin",
        "brioche",
        "rye bread",
        "flatbread",
        "dry-roasted peanuts",
        "potato chips",
        "stuffing mix",
        "taco shells",
        "naan",
        "cornbread",
        "tater tots",
        "unpopped popcorn",
        "corn chips",
        "bagel",
        "croissants",
        "pork rinds",
        "pumpernickel",
        "gluten free bread",
        "pita chips",
        "sweet bread",
        "hawaiian rolls",
        "potato bread",
        "breadsticks",
        "focaccia",
        "muffin",
        "tostada shells",
        "gluten-free bread crumbs",
        "crispy fried onions",
        "matzo",
        "garlic bread",
        "yeast extract spread",
        "challah",
        "roasted gram",
        "cheese crackers",
        "panettone",
        "crostini",
        "rice cake",
        "gluten-free tortillas",
        "cornbread stuffing mix",
        "sev",
        "sweet potato fries",
        "corn muffin",
        "papad",
        "vegetable chips",
        "spinach wraps",
        "plantain chips",
        "roasted chickpeas",
        "pretzel bun",
        "boboli",
        "cheetos",
        "chapati",
        "crispy noodles",
        "crumpet",
        "seed bread",
        "keto bread",
        "bread bowl",
        "low-carb wraps",
        "milk bread",
        "frozen onion rings",
        "sprouted grain bread",
        "rusks",
        "pav bun",
        "rice crackers",
        "corn nuts",
        "banana bread",
        "bread stuffing mix",
        "polarbr\u00f6d",
        "fruit bread",
        "sprouted bread",
        "crispbread",
        "roti bread",
        "puffed corn",
        "prawn crackers",
        "popcorn shrimp",
        "wasabi peas",
        "chocolate muffin",
        "ezekiel bread",
        "melba toast",
        "bao bun",
        "breading mix",
        "yorkshire pudding",
        "arabic bread",
        "barley rusks",
        "seaweed snack"
    ]
},
{
    "group_name": "Oils & Fats",
    "ingredients": [
        "olive oil",
        "vegetable oil",
        "extra virgin olive oil",
        "canola oil",
        "coconut oil",
        "cooking spray",
        "sesame oil",
        "frying oil",
        "sunflower oil",
        "avocado oil",
        "toasted sesame oil",
        "peanut oil",
        "grapeseed oil",
        "lard",
        "pork fat",
        "corn oil",
        "virgin coconut oil",
        "mustard oil",
        "chili oil",
        "garlic oil",
        "walnut oil",
        "truffle oil",
        "safflower oil",
        "cacao butter",
        "salad oil",
        "duck fat",
        "soybean oil",
        "rice bran oil",
        "medium-chain triglyceride",
        "white truffle oil",
        "butter-flavored cooking spray",
        "flaxseed oil",
        "pumpkin seed oil",
        "hazelnut oil",
        "coconut oil spray",
        "almond oil",
        "lemon oil",
        "macadamia oil",
        "goose fat",
        "palm oil",
        "basil oil",
        "schmaltz",
        "tallow",
        "pistachio oil",
        "algae oil",
        "herb-infused olive oil",
        "hot sesame oil",
        "pecan oil",
        "roasted peanut oil",
        "beef fat",
        "argan oil",
        "crisco oil",
        "shea butter",
        "black sesame oil",
        "red palm oil",
        "lamb fat",
        "sichuan peppercorn oil",
        "castor oil",
        "shallot oil",
        "achiote oil",
        "wheat germ oil",
        "blood orange olive oil",
        "jojoba oil",
        "oregano oil",
        "popcorn oil",
        "hemp seed oil",
        "cottonseed oil",
        "ginger oil",
        "rosehip seed oil",
        "marula oil",
        "white cacao butter",
        "black seed oil"
    ]
},
{
    "group_name": "Dressings & Vinegars",
    "ingredients": [
        "mayonnaise",
        "apple cider vinegar",
        "balsamic vinegar",
        "vinegar",
        "red wine vinegar",
        "rice wine vinegar",
        "white wine vinegar",
        "ranch dressing",
        "italian dressing",
        "sherry vinegar",
        "distilled white vinegar",
        "white balsamic vinegar",
        "sweet chilli sauce",
        "champagne vinegar",
        "balsamic vinaigrette",
        "vinaigrette dressing",
        "seasoned rice vinegar",
        "blue cheese dressing",
        "caesar dressing",
        "thousand island",
        "malt vinegar",
        "black vinegar",
        "canola mayonnaise",
        "raspberry vinegar",
        "japanese mayonnaise",
        "tarragon vinegar",
        "greek vinaigrette",
        "sesame dressing",
        "honey mustard dressing",
        "aioli sauce",
        "spicy mayo",
        "french dressing",
        "poppyseed dressing",
        "catalina dressing",
        "verjuice",
        "raspberry vinaigrette",
        "cane vinegar",
        "coleslaw dressing",
        "red wine vinaigrette",
        "russian dressing",
        "avocado oil mayonnaise",
        "buttermilk ranch dressing",
        "mustard-mayonnaise blend",
        "sushi vinegar",
        "champagne vinaigrette",
        "creamy balsamic dressing",
        "sun-dried tomato vinaigrette",
        "coconut vinegar",
        "ume plum vinegar",
        "garlic mayonnaise",
        "brown rice vinegar",
        "spicy ranch dressing",
        "cilantro dressing",
        "creamy dressing",
        "fig balsamic",
        "green goddess dressing",
        "chipotle aioli",
        "spiced vinegar",
        "lime vinaigrette",
        "onion salad dressing",
        "miso dressing",
        "white balsamic vinaigrette",
        "chardonnay vinegar",
        "honey vinegar",
        "hot-peppered vinegar",
        "lemon vinegar",
        "tandoori mayonnaise",
        "chili vinegar",
        "chili-lime dressing",
        "moscatel vinegar",
        "pomegranate vinegar",
        "vinegar powder",
        "mango vinaigrette",
        "sweet onion dressing",
        "avocado-lime dressing",
        "mustard aioli",
        "caramelised onion dressing"
    ]
},
{
    "group_name": "Condiments",
    "ingredients": [
        "soy sauce",
        "dijon mustard",
        "worcestershire",
        "hot sauce",
        "ketchup",
        "mustard",
        "fish sauce",
        "bbq sauce",
        "sriracha",
        "wholegrain mustard",
        "tamari",
        "oyster sauce",
        "chili sauce",
        "ginger-garlic paste",
        "brown mustard",
        "teriyaki sauce",
        "wing sauce",
        "prepared horseradish",
        "ginger paste",
        "dark soy sauce",
        "coconut aminos",
        "chili paste",
        "harissa",
        "chili-garlic sauce",
        "tamarind paste",
        "pomegranate molasses",
        "gochujang",
        "sambal oelek",
        "wasabi",
        "honey mustard",
        "mango chutney",
        "english mustard",
        "preserved lemon",
        "kecap manis",
        "chutney",
        "shrimp paste",
        "thai sweet chili sauce",
        "picante sauce",
        "sweet and sour sauce",
        "chili-garlic paste",
        "green chutney",
        "liquid aminos",
        "hot pepper jelly",
        "tartar sauce",
        "mexican hot sauce",
        "ponzu",
        "bonito flakes",
        "green chilli sauce",
        "red pepper jelly",
        "thai chili paste",
        "crispy onions",
        "peri peri",
        "green chilli paste",
        "red pepper relish",
        "mint jelly",
        "aji amarillo",
        "horseradish mustard",
        "mustard paste",
        "tamarind chutney",
        "ginger chili paste",
        "onion marmalade",
        "yuzu juice",
        "giardiniera",
        "chermoula",
        "duck sauce",
        "hp sauce",
        "tonkatsu sauce",
        "doubanjiang",
        "chili crisp",
        "black soy sauce",
        "doenjang",
        "korean bbq sauce",
        "maggi sauce",
        "lime pickle",
        "chinese mustard",
        "karashi",
        "chamoy",
        "mushroom soy sauce",
        "taucheo",
        "german mustard",
        "yuzu kosho",
        "banana ketchup",
        "remoulade",
        "hot pepper relish",
        "patis",
        "pickapeppa sauce",
        "eel sauce",
        "guk ganjang",
        "hot bean paste",
        "salsa lizano",
        "white bbq sauce",
        "biber salcasi",
        "grape must",
        "shrimp sauce",
        "shrimp powder",
        "chili puree",
        "fermented tofu",
        "green harissa",
        "sweet soybean paste",
        "szechuan sauce"
    ]
},
{
    "group_name": "Canned Food",
    "ingredients": [
        "canned tomato",
        "capers",
        "green olives",
        "canned chickpea",
        "black olives",
        "canned black beans",
        "canned pumpkin",
        "canned pineapple",
        "kalamata olives",
        "canned tuna",
        "pickle",
        "chipotle in adobo",
        "roasted red peppers",
        "canned anchovy",
        "maraschino cherry",
        "tomatoes with green chiles",
        "canned kidney beans",
        "canned whole tomato",
        "canned artichoke",
        "canned corn",
        "canned pie filling",
        "refried beans",
        "canned cannellini beans",
        "sweet pickle relish",
        "sauerkraut",
        "creamed corn",
        "corned beef",
        "canned beans",
        "pickled jalapenos",
        "diced green chiles",
        "canned pinto beans",
        "sun-dried tomatoes in oil",
        "canned mandarin oranges",
        "kimchi",
        "chili beans",
        "canned crab",
        "canned peaches",
        "bamboo shoot",
        "baked beans",
        "canned mushroom",
        "canned salmon",
        "pickling juice",
        "dill pickle relish",
        "canned clam",
        "canned water chestnut",
        "canned black-eyed peas",
        "canned whole green chiles",
        "pickled ginger",
        "canned apple",
        "canned green beans",
        "spam",
        "hearts of palm",
        "chili with beans",
        "pickled onions",
        "canned lentils",
        "canned peas",
        "fruit cocktail",
        "grape leaves",
        "pickled red onion",
        "pimiento-stuffed green olives",
        "canned pork",
        "pickled beets",
        "canned cherry tomato",
        "bread & butter pickles",
        "canned apricot",
        "canned sweet potato",
        "canned sour cherry",
        "canned pear",
        "peppadew pepper",
        "pork and beans",
        "onion paste",
        "canned baby corn",
        "pickled vegetables",
        "chili without beans",
        "mexican-style corn",
        "pumpkin pie filling",
        "fire-roasted green chiles",
        "pickled pepper",
        "banana pepper rings",
        "ranch-style beans",
        "canned chicken breast",
        "canned carrot",
        "canned cherry",
        "canned lychee",
        "canned sardines",
        "canned mixed beans",
        "canned lima beans",
        "ginger in syrup",
        "taggiasca olives",
        "canned jackfruit",
        "canned potato",
        "tomato relish",
        "canned mango",
        "cranberry relish",
        "pickled herring",
        "canned asparagus",
        "canned fava beans",
        "canned peas and carrots",
        "florina peppers",
        "corn relish"
    ]
},
{
    "group_name": "Sauces, Spreads & Dips",
    "ingredients": [
        "tomato paste",
        "peanut butter",
        "tomato sauce",
        "salsa",
        "tahini",
        "pesto",
        "pasta sauce",
        "marinara sauce",
        "hoisin sauce",
        "pico de gallo",
        "enchilada sauce",
        "stewed tomatoes",
        "guacamole",
        "hummus",
        "salsa verde",
        "fire-roasted tomato",
        "alfredo sauce",
        "balsamic glaze",
        "anchovy paste",
        "steak sauce",
        "chunky peanut butter",
        "tzatziki",
        "beef gravy",
        "taco sauce",
        "sun-dried tomato pesto",
        "green enchilada sauce",
        "red pepper hummus",
        "cheese dip",
        "b\u00e9chamel sauce",
        "horseradish sauce",
        "plum sauce",
        "garlic butter",
        "hollandaise sauce",
        "cocktail sauce",
        "tapenade",
        "black bean sauce",
        "pimento cheese spread",
        "stir-fry sauce",
        "turkey gravy",
        "thai peanut sauce",
        "chicken gravy",
        "sloppy joe sauce",
        "demi-glace",
        "sofrito",
        "mustard sauce",
        "french onion dip",
        "chimichurri sauce",
        "sun-dried tomato paste",
        "herb butter",
        "bolognese sauce",
        "curry sauce",
        "browning sauce",
        "liver spread",
        "schezwan sauce",
        "pork gravy",
        "country gravy",
        "orange sauce",
        "pineapple salsa",
        "mushroom gravy",
        "chicken demi-glace",
        "mango salsa",
        "olive paste",
        "spinach dip",
        "artichoke dip",
        "japanese curry",
        "black sesame paste",
        "black truffle butter",
        "whipped cream cheese spread",
        "bacon jam",
        "tikka masala sauce",
        "vodka sauce",
        "garlic hummus",
        "green taco sauce",
        "kung pao sauce",
        "sausage gravy",
        "corn salsa",
        "mole paste",
        "onion gravy",
        "pad thai sauce",
        "cheddar sauce",
        "cheese spread",
        "deviled ham spread",
        "butter chicken sauce",
        "garlic pasta sauce",
        "garlic spread",
        "black pepper sauce",
        "char siu sauce",
        "sesame sauce",
        "schezwan chutney",
        "thai red curry sauce",
        "green olive tapenade",
        "kale pesto",
        "tarama",
        "white pizza sauce",
        "white truffle butter",
        "mango sauce",
        "nuoc cham",
        "salsa con queso dip",
        "ssamjang",
        "yum yum sauce"
    ]
},
{
    "group_name": "Soups, Stews & Stocks",
    "ingredients": [
        "chicken broth",
        "vegetable broth",
        "chicken stock",
        "beef broth",
        "beef stock",
        "bouillon cube",
        "cream of mushroom",
        "cream of chicken",
        "onion soup mix",
        "tomato soup",
        "fish stock",
        "cream of celery",
        "clam juice",
        "cheese soup",
        "soup base",
        "bone broth",
        "dashi",
        "onion soup",
        "veal stock",
        "chicken bone broth",
        "chicken stock paste",
        "turkey stock",
        "lamb stock",
        "turkey broth",
        "beef consomm\u00e9",
        "cream of potato",
        "golden mushroom soup",
        "seafood stock",
        "beef base",
        "chicken soup",
        "mushroom broth",
        "turkey drippings",
        "vegetable soup mix",
        "chicken noodle soup",
        "vegetable soup",
        "ramen noodle soup",
        "nacho cheese soup",
        "shrimp stock",
        "tomato bouillon",
        "beef dripping",
        "lobster stock",
        "pork stock",
        "chicken rice soup",
        "cream of broccoli",
        "beefy onion soup mix",
        "clam broth",
        "butternut squash soup",
        "miso soup",
        "broccoli-cheese soup",
        "duck stock",
        "sinigang mix",
        "vegan chicken broth",
        "cream of asparagus",
        "new england clam chowder",
        "beefy mushroom soup",
        "ham stock",
        "pork broth",
        "cream of shrimp soup",
        "bean soup mix",
        "black bean soup",
        "condensed chicken gumbo soup",
        "chicken consomm\u00e9",
        "cream of bacon",
        "lentil soup",
        "veal broth",
        "vegetable beef soup",
        "chicken soup mix",
        "roasted garlic chicken broth",
        "lobster bisque",
        "bean with bacon soup",
        "clam chowder",
        "thai ginger broth",
        "tortilla soup base",
        "anchovy stock",
        "chicken drippings",
        "chicken corn chowder",
        "cream of chicken soup mix",
        "shrimp bouillon cube",
        "thai chicken broth",
        "lamb broth",
        "minestrone",
        "pork & beans",
        "tomato bisque",
        "turkey bone broth",
        "vegan beef broth",
        "venison stock",
        "bovril",
        "turkey base",
        "ham-flavored concentrate",
        "noodle soup mix",
        "potato soup mix",
        "callaloo",
        "oxtail soup",
        "split pea soup",
        "chili beef soup",
        "corn chowder",
        "cream of cauliflower",
        "dashida",
        "green pea soup",
        "pho broth"
    ]
},
{
    "group_name": "Desserts & Sweet Snacks",
    "ingredients": [
        "cocoa",
        "dark chocolate",
        "dark cocoa",
        "chocolate",
        "marshmallow",
        "applesauce",
        "gelatin",
        "white chocolate",
        "graham cracker",
        "graham cracker crumbs",
        "oreo",
        "instant pudding",
        "chocolate hazelnut spread",
        "dutch-process cocoa",
        "chocolate candy",
        "raspberry jam",
        "caramel sauce",
        "biscuits",
        "apricot jam",
        "candy coating",
        "raw cacao powder",
        "strawberry jam",
        "marshmallow creme",
        "candy",
        "baking chocolate",
        "orange marmalade",
        "wafer",
        "jam",
        "cookies",
        "jello",
        "cranberry sauce",
        "chocolate pudding",
        "peanut butter cups",
        "candy cane",
        "ginger snaps",
        "cacao nibs",
        "lady fingers",
        "fudge sauce",
        "caramel candies",
        "chocolate cookies",
        "apple butter",
        "peppermint candy",
        "cinnamon roll",
        "candied cherry",
        "butter cookies",
        "currant jelly",
        "candied ginger",
        "angel food cake",
        "couverture chocolate",
        "peach preserves",
        "chocolate chip cookies",
        "candied peel",
        "dark couverture chocolate",
        "cherry jam",
        "white baking chocolate",
        "chocolate wafer",
        "instant lemon pudding",
        "fig jam",
        "grape jelly",
        "waffles",
        "agar agar",
        "cookie butter",
        "candied fruit",
        "apple jelly",
        "gummies",
        "blackberry preserves",
        "candy corn",
        "almond cookies",
        "blueberry jam",
        "chocolate-covered nougat",
        "butterscotch",
        "ice-cream cone",
        "egg candies",
        "sugar cookies",
        "strawberry puree",
        "marmalade",
        "chocolate powder",
        "licorice",
        "pineapple jam",
        "banana pudding",
        "chocolate-covered espresso bean",
        "sponge cake",
        "mexican chocolate",
        "sorbet",
        "plum jam",
        "white couverture",
        "cinnamon candy",
        "white chocolate pudding",
        "peanut-butter sandwich cookies",
        "pumpkin butter",
        "chocolate peanut butter",
        "guava paste",
        "butterscotch pudding mix",
        "cheesecake instant pudding",
        "chocolate spread",
        "strawberry sauce",
        "hershey kisses",
        "doughnut",
        "fudge",
        "biscotti"
    ]
},
{
    "group_name": "Wine, Beer & Spirits",
    "ingredients": [
        "white wine",
        "red wine",
        "whisky",
        "rum",
        "vodka",
        "beer",
        "orange liqueur",
        "cider",
        "tequila",
        "sherry",
        "gin",
        "brandy",
        "bitters",
        "mirin",
        "white rum",
        "coffee liqueur",
        "champagne",
        "vermouth",
        "irish cream",
        "amaretto",
        "cognac",
        "marsala wine",
        "sparkling wine",
        "sake",
        "shaoxing wine",
        "rice wine",
        "dry vermouth",
        "coconut rum",
        "curacao",
        "liqueur",
        "dessert wine",
        "port wine",
        "kirsch",
        "peach schnapps",
        "white cooking wine",
        "apple brandy",
        "ros\u00e9 wine",
        "anise liqueur",
        "herbal liqueur",
        "limoncello",
        "elderflower liqueur",
        "hazelnut liqueur",
        "raspberry liqueur",
        "melon liqueur",
        "peach liqueur",
        "banana liqueur",
        "schnapps",
        "creme de cacao",
        "absinthe",
        "madeira wine",
        "aperol",
        "vanilla vodka",
        "cinnamon alcohol",
        "creme de menthe",
        "apricot brandy",
        "cacha\u00e7a",
        "chocolate liqueur",
        "elderflower cordial",
        "b\u00e9n\u00e9dictine",
        "ginger liqueur",
        "sloe gin",
        "creme de cassis",
        "maraschino",
        "red cooking wine",
        "cream sherry",
        "bloody mary mix",
        "gold rum",
        "sparkling ros\u00e9",
        "lime cordial",
        "drambuie",
        "grappa",
        "strawberry liqueur",
        "galliano",
        "mezcal",
        "ginger wine",
        "peppermint liqueur",
        "rumchata",
        "white port",
        "pi\u00f1a colada mix",
        "pumpkin ale",
        "advocaat",
        "daiquiri mix",
        "blackberry schnapps",
        "coconut liqueur",
        "blackberry brandy",
        "gentian liqueur",
        "chocolate bitters",
        "vanilla liqueur",
        "moonshine",
        "pisco",
        "plum wine",
        "grapefruit bitters",
        "peach brandy",
        "sangria",
        "gluten-free beer",
        "white chocolate liqueur",
        "apple liqueur",
        "pear brandy",
        "apple vodka",
        "rhum agricole"
    ]
},
{
    "group_name": "Beverages",
    "ingredients": [
        "orange juice",
        "coffee",
        "club soda",
        "espresso",
        "pineapple juice",
        "apple juice",
        "tea",
        "cranberry juice",
        "tomato juice",
        "coconut water",
        "pomegranate juice",
        "matcha powder",
        "grapefruit juice",
        "coke",
        "lemonade",
        "eggnog",
        "ginger ale",
        "ginger beer",
        "orange juice concentrate",
        "lemon lime soda",
        "sprite",
        "cream of coconut",
        "green tea",
        "lemonade concentrate",
        "root beer",
        "chai tea",
        "drinking chocolate",
        "tonic water",
        "malted milk powder",
        "sour mix",
        "cherry juice",
        "mango juice",
        "hibiscus",
        "tea leaves",
        "grape juice",
        "limeade concentrate",
        "carrot juice",
        "dr pepper",
        "iced tea",
        "fruit juice",
        "watermelon juice",
        "white grape juice",
        "tangerine juice",
        "kombucha",
        "passion-fruit juice",
        "apricot juice",
        "orange soda",
        "peach juice",
        "beet juice",
        "margarita mix",
        "energy drink",
        "kool aid",
        "pear juice",
        "chamomile tea",
        "cream soda",
        "mountain dew",
        "tamarind water",
        "tamarind juice",
        "rooibos tea",
        "grapefruit soda",
        "lime soda",
        "raspberry juice",
        "clamato",
        "guava juice",
        "jasmine tea",
        "iced coffee concentrate",
        "strawberry juice",
        "green tea leaves",
        "rose syrup",
        "v8 juice",
        "sweetened lime juice",
        "blueberry juice",
        "lemonade mix",
        "beetroot juice",
        "thai tea",
        "pineapple juice concentrate",
        "aloe vera juice",
        "juice blend",
        "butterfly pea flower",
        "lapsang souchong",
        "prune juice",
        "berry juice",
        "passion tea",
        "sparkling cider",
        "white tea",
        "strawberry soda",
        "blackcurrant juice",
        "peppermint tea",
        "lychee juice",
        "frapp\u00e9 base",
        "herbal tea",
        "banana juice",
        "chicory coffee",
        "cranberry-raspberry juice",
        "cherry soda",
        "raspberry lemonade",
        "decaf coffee",
        "pumpkin spice coffee",
        "lemon water",
        "bitter lemon soda"
    ]
},
{
    "group_name": "Supplements & Extracts",
    "ingredients": [
        "almond extract",
        "food coloring",
        "nutritional yeast",
        "peppermint extract",
        "protein powder",
        "lemon extract",
        "coconut extract",
        "rose water",
        "orange extract",
        "rum extract",
        "rock salt",
        "maple extract",
        "chocolate protein powder",
        "collagen",
        "orange blossom water",
        "peanut butter powder",
        "vegan protein powder",
        "citric acid",
        "maca powder",
        "strawberry extract",
        "essence",
        "spirulina",
        "brewer's yeast",
        "coffee extract",
        "butter extract",
        "anise extract",
        "chocolate extract",
        "raspberry extract",
        "lavender oil",
        "cannabis",
        "banana extract",
        "bee pollen",
        "essential oil",
        "caramel extract",
        "root beer extract",
        "vitamin c",
        "cannabutter",
        "acai powder",
        "cinnamon extract",
        "hemp protein",
        "ube flavoring",
        "hazelnut extract",
        "glucomannan",
        "tamarind extract",
        "butterscotch flavor",
        "cherry extract",
        "kewra water",
        "pineapple extract",
        "freeze-dried strawberry powder",
        "lucuma powder",
        "lemon juice concentrate",
        "cannabis milk",
        "carnation breakfast essentials",
        "lime concentrate",
        "kombucha starter",
        "lime essential oil",
        "casein",
        "malt extract",
        "chocolate collagen",
        "pandan extract",
        "camu powder",
        "ashwagandha",
        "wheatgrass powder",
        "soy lecithin",
        "apple extract",
        "cbd oil",
        "chlorella",
        "rosemary essential oil",
        "mango extract",
        "probiotics",
        "tea-tree oil",
        "fish oil",
        "reishi mushroom",
        "vitamin e",
        "rice protein powder",
        "activated charcoal",
        "corn extract",
        "grapefruit essential oil",
        "maltodextrin",
        "wine yeast",
        "barley grass",
        "clove oil",
        "greens powder",
        "vitamin d",
        "blueberry extract",
        "calcium lactate",
        "raspberry powder",
        "sunflower lecithin",
        "thc",
        "banana powder",
        "berry powder",
        "champagne yeast",
        "creatine",
        "magnesium",
        "maqui",
        "moringa powder",
        "rose oil",
        "sodium alginate",
        "cake batter extract",
        "chaga mushroom powder"
    ]
}
];

export default allIngredients;